### ISSUE TITLE
TransactionBuilderHelper.GetUnspent() fails with ArgumentNullException

### ISSUE THREAD

**Issue by l-vitall** [CityOfZion/NeoModules#10] opened 2019-01-09 15:49 UTC
I suppose it fails here:
Output = new TransactionOutput
                                      {
...
                                          AssetId = UInt256.Parse(balanceEntry.AssetHash),
...
                                      }
because balanceEntry.AssetHash is null (restService returns null at least for local private network)

Native coins transfer does not work because of this issue (AccountSignerTransactionManager.SendNativeAsset())

**Comment by BrunoFreitasgit** [comment] 2019-01-14 17:08
I can't reproduce a null value there, but I added null checker. If it persists, feel free to open this issues and maybe PR a fix.

**Comment by l-vitall** [comment] 2019-01-22 15:20
It still fails with same exception. The problem is in UInt256.Parse(balanceEntry?.AssetHash) code, I checked in debagger that exactly this row throws an exception because balanceEntry?.AssetHash is null.

**Comment by BrunoFreitasgit** [comment] 2019-01-22 15:25
I do not have a private neoscan network running, so I cannot see why this is happening. Maybe you can submit a PR?

**Comment by BrunoFreitasgit** [comment] 2019-01-22 15:37
https://help.github.com/articles/about-pull-requests/

**Comment by l-vitall** [comment] 2019-01-23 17:06
To fix it I modified NeoModules.Rest/Services/NeoscanRestService.cs:
1. Added at the file beginning:
`private static Dictionary<string, string> assetsDict = new Dictionary<string, string>(){
            { "NEO", "c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b"},
            { "GAS", "602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7"}
        };`
2. Modified GetBalanceAsync(string address) with this ending:
`var addressBalance = AddressBalance.FromJson(data);
            foreach (var balance in addressBalance.Balance)
            {
                if (string.IsNullOrWhiteSpace(balance.AssetHash))
                    balance.AssetHash = assetsDict[balance.Asset];
            }
            return addressBalance;`
Now transaction worked with privateNet. Please let me know if PR is needed.
Question 1: How often NeoModules NuGet is being updated? I need it in my solution, can we push this change to NuGet pavkage?
Question 2: I can provide private net docker (privateNet, neo-scan, neo-cli) if neeed

**Comment by BrunoFreitasgit** [comment] 2019-01-23 17:39
cannot understand how does this work.. Just looked to the Neoscan API docs again, and it has a field "asset_hash". So if returns null from the private API, I think the problem is in your end. But I will think on a way to reduce dependencies on this.

1) I update often when there are critical bugs or major improvements. Since I think that what you posted is not a fix, i will not update. Also, instead of pasting code in here, just do a PR, easier for both of us.

**Comment by l-vitall** [comment] 2019-01-24 08:42
I used neo-scan docker recommended here: https://hub.docker.com/r/cityofzion/neo-privatenet. I can see the ticket 'Update NeoScan to latest release' on the neo-scan docker GitHub, so possibly it is not the latest version and that is the reason of issue. But I cannot find better docker and I cannot use different code for my automated unit tests and for production environment. This is the official recommendation to debug with local privateNet, then test with testNet and after them move to mainNet. May be it is my end issues, but currently it is a deal stopper. And I believe it is a deal stopper not for me only. I cannot use NeoModules because of this failure and have to search for workarounds.

**Comment by BrunoFreitasgit** [comment] 2019-01-25 16:05
Closing this, see https://github.com/CityOfZion/NeoModules/pull/13#issuecomment-457622570

**Closed by BrunoFreitasgit** 2019-01-25 16:05 UTC

**Comment by l-vitall** [comment] 2019-02-02 10:01
For ones who can have the same issue as described: neo-local can be used as up-to-date private network neo-scan implementation. I do not know why there are so many services and what purpose of all of them, but it works. I was able to remove some of services and it still works as private net + neo-scan + recent neo-python that hosts RPC endpoint. NeoModules works fine with this set.
